### ISSUE TITLE
Create a logo for knuu

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#125]

**Comment by mohitvdx** [comment]
I can work on this, if this is not assigned

**Comment by smuu** [comment]
> I can work on this, if this is not assigned

@mohitvdx I assigned you to the issue

**Comment by smuu** [comment]
> okay. Is there something specific I should keep in mind while designing the logo?

No, there is nothing specific. You have all the freedom to design the logo @mohitvdx :+1:

**Comment by smuu** [comment]
done
