### ISSUE TITLE
Change labels to contain `knuu.sh/` prefix to avoid conflicts

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#132]
- test-run-id
- test-started
- name
- k8s-name
- type

**Comment by Najamulhassan3383** [comment]
Hi @smuu 
I am new to Open source and this is my first time contributing to it.  I am not able to understand the issue, can you plz explain it a bit like what and where to change.
It would be highly appreciated . Thanks

**Comment by smuu** [comment]
Hi @Najamulhassan3383,

Firstly, welcome to the open-source world! It's great to see new contributors like yourself.

This issue is about modifying the labels used in our Kubernetes objects. In the codebase, we have a function `getLabels()` that returns a map of labels. These labels are used to identify and manage Kubernetes objects. The function is in the file `instance_helper.go` in line 59.

Here's the current function:

```go
func (i *Instance) getLabels() map[string]string {
	return map[string]string{
		"app":                          i.k8sName,
		"k8s.kubernetes.io/managed-by": "knuu",
		"test-run-id":                  identifier,
		"test-started":                 startTime,
		"name":                         i.name,
		"k8s-name":                     i.k8sName,
		"type":                         i.instanceType.String(),
	}
}
```

The issue is requesting that we add the prefix `knuu.sh/` to certain labels to avoid conflicts. The labels that need to be updated are:

- test-run-id
- test-started
- name
- k8s-name
- type

So, the updated function should look like this:

```go
func (i *Instance) getLabels() map[string]string {
	return map[string]string{
		"app":                          i.k8sName,
		"k8s.kubernetes.io/managed-by": "knuu",
		"knuu.sh/test-run-id":          identifier,
		"knuu.sh/test-started":         startTime,
		"knuu.sh/name":                 i.name,
		"knuu.sh/k8s-name":             i.k8sName,
		"knuu.sh/type":                 i.instanceType.String(),
	}
}
```

Please note that you'll also need to update any references to these labels elsewhere in the codebase. This means that if a piece of code is looking for the label "test-run-id", you'll need to change it to look for "knuu.sh/test-run-id" instead.

I hope this helps! If you have any more questions, feel free to ask. And by the way, this message is generated by GPT-4.

**Comment by Najamulhassan3383** [comment]
@smuu I have opened a PR for this issue. Plz let me know if there is any issue. Thanks
