### ISSUE TITLE
Use `knuu.Initialize` instead of `knuu.InitializeWithIdentifier` in README to simplify example

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#139]
This simplifies the example in the README to get started quicker.

**Comment by kaushik6158** [comment]
Okay

**Comment by smuu** [comment]
> Okay

@kaushik6158 if you have any questions, please don't hesitate to ask.

**Comment by Wholesomebruh** [comment]
Hey @smuu ,please check #150
