### ISSUE TITLE
Update feature list in `README` with issues done in https://github.com/celestiaorg/knuu/issues/91

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#141]
https://github.com/celestiaorg/knuu/issues/91

**Comment by Mackenzie-OO7** [comment]
Hi @smuu can I be assigned to this?

**Comment by smuu** [comment]
> Hi @smuu can I be assigned to this?

@Mackenzie-OO7 the issue is now assigned to you :+1:

**Comment by smuu** [comment]
we work on the README in other issues
