### ISSUE TITLE
Use namespace from context as default kubernetes namespace

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#144]
Currently, the namespace is `test` if not specified otherwise, using the `KNUU_NAMESPACE` environment variable.

See here in the code:

https://github.com/celestiaorg/knuu/blob/main/pkg/k8s/k8s.go#L43

Instead of using `test` as default, it knuu should use the namespace selected in the `kubeconfig` if the environment variable `KNUU_NAMESPACE` is not set.

**Comment by Wholesomebruh** [comment]
Hey @smuu , changing the L41-48 
```go
else {
		// Read the namespace from KNUU_NAMESPACE environment variable
		if os.Getenv("KNUU_NAMESPACE") != "" {
			setNamespace(os.Getenv("KNUU_NAMESPACE"))
		} else {
			setNamespace("test")
		}
	}
```
with
```go
else {
		// Read the namespace from the kubeconfig file
		namespace, err := clientcmd.NewDefaultClientConfigLoadingRules().Namespace()
		if err != nil {
			return fmt.Errorf("retrieving namespace from kubeconfig: %w", err)
		} else{
			setNamespace(namespace)
		}
	}
```
will resolve the issue . Please confirm this.

**Comment by smuu** [comment]
We have scopes now
