### ISSUE TITLE
Add Port Check to Destroy Function to Match Start Function Behavior

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#147]
When calling `Start` the code checks if ports and only deploys a service if so.

https://github.com/celestiaorg/knuu/blob/920d628be85f2670857a962e78481666994feea2/pkg/knuu/instance.go#L619

In the `Destroy`, we don't have this check. We just call the destroy function.

https://github.com/celestiaorg/knuu/blob/920d628be85f2670857a962e78481666994feea2/pkg/knuu/instance.go#L777

Add the same check to the `Destroy` as we have in `Start` for the Kubernetes service.

**Comment by Frenzoid** [comment]
@smuu check this out :) https://github.com/celestiaorg/knuu/pull/149

**Comment by smuu** [comment]
outdated, done differently
