### ISSUE TITLE
Consider adding support for `.env` file

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#153]

**Comment by mohitvdx** [comment]
Hey @smuu Could you elaborate a bit more? I can work on this.

**Comment by anands8196** [comment]
Please explain or elaborate? @smuu

**Comment by smuu** [comment]
Thanks, @mohitvdx and @anands8196 that you want to contribute.

Currently, there is one environment variable to change the behavior of the test run: `KNUU_TIMEOUT`. There will most likely be more environmental variables.
To use those variables, you export them to your system or add them to the test command, which is unhandy when setting multiple variables. Therefore, the idea is to have a file called `.env` where the user can set the environment variables. To support that file, knuu must read that file.

I need to find out the implementation details, I would need to research them.

**Comment by smuu** [comment]
done
