### ISSUE TITLE
Use `HasResource` instead of `ResourceExists` in `k8s` package

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#160]
```
[nit][non-blocking]: we can have semantically a different name like `func HasConfigMap(namespace, name string)`

this ofc will imply that DaemonSetExists should be converted to similar fashion
```

_Originally posted by @Bidon15 in https://github.com/celestiaorg/knuu/pull/154#discussion_r1265227438_

**Comment by akp111** [comment]
Hey @smuu , is this still valid, would love to work on this

**Comment by smuu** [comment]
> Hey @smuu , is this still valid, would love to work on this

Hey @akp111! Yes this issue is still valid. I just assigned you to the issue.

Please remember to check all files in the `k8s` package and update the corresponding functions and the usage of those throughout the project.

In case you have any questions, please don't hesitate to ask.

**Comment by akp111** [comment]
Hey @smuu , thank you very much. So, just to be sure I am clear about it. The goal is to essentially replace `HasConfigMap ` with `ConfigMapExists`

**Comment by smuu** [comment]
> Hey @smuu , thank you very much. So, just to be sure I am clear about it. The goal is to essentially replace `HasConfigMap ` with `ConfigMapExists`

That's the first step. Then the idea is to replace those `Has` functions with `Exists` for all resources, not only ConfigMap.

**Comment by mojtaba-esk** [comment]
@smuu can this issue be closed?

**Comment by smuu** [comment]
> @smuu can this issue be closed?

Yes, this is already done.
