### ISSUE TITLE
add configMap to timeoutHandler

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#164]
Currently, ConfigMaps are not deleted by the timeoutHandler.

Change the command of the timeout handler so that configMaps are deleted.

https://github.com/celestiaorg/knuu/blob/fd85a081e5c0e9472d0a739b94d8d3807784edb1/pkg/knuu/knuu.go#L107
https://github.com/celestiaorg/knuu/blob/fd85a081e5c0e9472d0a739b94d8d3807784edb1/pkg/knuu/knuu.go#L108

**Comment by lazyfuhrer** [comment]
Assign me @smuu

**Comment by smuu** [comment]
> Assign me @smuu

There you go @lazyfuhrer
