### ISSUE TITLE
Point out in `README.md` that the default max test run is 1h

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#165]
This is due to the timeout handler with a default timeout value of 1h. This default can be changed with `KNUU_TIMEOUT`.

**Comment by web3metaversee** [comment]
Like 😉

**Comment by AnmolSirola** [comment]
@smuu Can I work on this issue ?

**Comment by smuu** [comment]
> @smuu Can I work on this issue ?

Yes @AnmolSirola, I just assigned the issue to you.
If you have any questions, don't hesitate to contact me :+1:

**Comment by AnmolSirola** [comment]
@smuu Can you please tell me where in the documentation I need to make the required changes?

**Comment by smuu** [comment]
done
