### ISSUE TITLE
Add function to check whether a docker container exists

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/knuu#199]
I'm not sure if there is an existing issue for this, but it would be helpful if there was some method I could run to check whether a docker container existed before pulling it. This way I can return a helpful error to the caller in the tests (since version is injected to the go tests)

**Comment by smuu** [comment]
I will think about this. I do not have anything straight forward in my head atm.

**Comment by smuu** [comment]
This is not required as we have the Preloader, which ensures an image is available on all k8s nodes.
