### ISSUE TITLE
Test instances orchestration

### ISSUE THREAD

**Issue by mojtaba-esk** [celestiaorg/knuu#215]
## Problem

Currently if we want to shape the traffic with `Knuu+BitTwsiter`, we need to expose the address & ports of the pod running the target instance with a sidecar running BitTwister to be able to access to BitTwister from Knuu. The main reason is because Knuu is running from above and creates instances, configures them and runs them.

### Reverse proxy
@smuu please fill this section with the idea

### Distributed Playbook

Since most (if not all) tests have plans before hand, it is known when and how to shape the traffic. The playbook idea is a way similar to what testground is doing, and it is the following:

1. User defines the test scenario using e.g. golang or some other descriptive language can be just a JSON file
2. Knuu initiates the instances and assigns each playbook to their corresponding instance
3. BitTwister is running in a sidecar with some extra code that understand the playbook
4. It changes the traffic shape at the time that is required. it can be any given event from the target instance.

**Advantages:** 

1. No need for a centralized entity to instruct each instance what to do. Everyone knows what to do beforehand just a like a bee.
2. No need to expose IP addresses or using a proxy for the `control data`

**Comment by Bidon15** [comment]
Thinking more and discussing on the call, @mojtaba-esk brought a good point that actually we want the test designer or implementor to know the scenarios / program them way before runtime as steps and expected/actual results. 
Which knuu at the current stage is not doing so, providing interactive synchronous calls design. 

Considering that our testing tools are still in user discovery phase (no one in core eng have explicitly expresses that they prefer sync more than async, vice versa), not spending time on reverse proxy and double down on v1 of knuu that will be async only(user should know & code the test behaviour before runtime and the execution is happening without any vanilla interactive approach) will be a big win to marry the testground distributed design and knuu easiness of use

**Comment by Bidon15** [comment]
That being said I see the following: 

- v0 -> park it as done with helper functions that just encloses the UX struggle with port forwardings
- v1 -> separate branch, where we have an ADR to gather rough consensus on foundation of new tests and move on with implementation details

**Comment by smuu** [comment]
I like the idea!
I don't know if using port forwarding for now is sufficient, as errors with port forwarding are inconsistent. Callum had issues having ~9 port forwardings at a time, but it worked for me.

**Comment by Bidon15** [comment]
> I like the idea! I don't know if using port forwarding for now is sufficient, as errors with port forwarding are inconsistent. Callum had issues having ~9 port forwardings at a time, but it worked for me.

I think this is also a good point why we want to enclose this into the test itself and not let people do interactive style. The only thing we can do for those use-cases is to use a scaleway instance and move on

**Comment by mojtaba-esk** [comment]
As BitTwister now is integrated in knuu and is working, should we close this issue?
@jrmanes @smuu
