### ISSUE TITLE
Minio per test run

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#258]
maybe have minio as a instance

**Comment by mojtaba-esk** [comment]
What is the usage of minio while the target instance (e.g. celestia app) is not instrumented? can you please give a use case example?

**Comment by mojtaba-esk** [comment]
aha ok, we have a code to prepare and eploy minio as a service so that could be re-used. in fact if we use kaniko and pass a local directory to build the image on k8s, it is uploaded to minio and kaniko reads from it. so that service could be used. I will put it in my todo list.
