### ISSUE TITLE
Create new method `StartAsync` and point to an existing one

### ISSUE THREAD

**Issue by tty47** [celestiaorg/knuu#271]
This is a simple one, create a new Instance method called `StartAsync` and point to `StartWithoutWait`
https://github.com/celestiaorg/knuu/blob/main/pkg/knuu/instance.go#L972

We will deprecate `StartWithoutWait` in the newer versions.

**Comment by k124k3n** [comment]
```go
func StartAsync(){
    StartWithoutWait()
}
```

Like this?
