### ISSUE TITLE
Add Functionality to Fetch Entire Folder Content from Knuu Instance

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/knuu#272]
## Problem

When there's a need to retrieve the content of a folder from a Knuu instance, users must individually specify each file by invoking  `GetFileBytes` function, which only supports reading single files. To streamline this process, it would be highly beneficial to implement a feature that allows fetching all the files/subfolders within a folder without needing to name each of them individually.  

## Acceptance Criteria
- [ ]  Adding a function or expanding the existing `GetFileBytes` to support retrieval of an entire folder's content

**Comment by mojtaba-esk** [comment]
@staheri14 is it mostly required on a running instance or an instance that has not started yet?

**Comment by staheri14** [comment]
> @staheri14 is it mostly required on a running instance or an instance that has not started yet?

We need to pull data from a  running instance.

**Comment by smuu** [comment]
not needed right now, low prio

**Comment by smuu** [comment]
Duplicate off https://github.com/celestiaorg/knuu/issues/292
