### ISSUE TITLE
Separate Bittwister Networking Test from DisableNetwork Functionality

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/knuu#294]
I just realized we combined DisableNetwork() and Bittwister. For me, this does not make sense. Disabling the network does not allow connections to that Instance, but as we want to check Bittwister, this should not be used here.
I propose to move the Bittwister networking test to a separate file and keep the existing one with disabling network.

Originally posted by @smuu in https://github.com/celestiaorg/knuu-example/pull/63#pullrequestreview-1812871344

based on the knuu-example one: https://github.com/celestiaorg/knuu-example/issues/64

**Comment by mojtaba-esk** [comment]
Let's close it as it is already done
