### ISSUE TITLE
refactor!: have knuu as an object

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#328]
```go
func Knuu(scope string) (*Knuu, error)

func (k *Knuu) GetScope() (string, error)
func (k *Knuu) CleanUp() (error)
func (k *Knuu) SetImageBuilder(b builder.Builder) (error)
func (k *Knuu) ImageBuilder() (builder.Builder, error)
func (k *Knuu) NewInstance(name string) error
```

If we do that before `v1`, please make changes backward compatible.

**Comment by mojtaba-esk** [comment]
This is a breaking change, we need to communicate it well to the users before cutting a release.

**Comment by smuu** [comment]
> This is a breaking change, we need to communicate it well to the users before cutting a release.

Can we add this without touching the current code?

**Comment by mojtaba-esk** [comment]
We can write some wrappers to support the current users, then in another release we can get rid of the wrapper and ask everyone to use it as an object.
