### ISSUE TITLE
Execute command in Instance when in state Preparing always returns an empty string

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#34]

**Comment by smuu** [comment]
Needs to be discussed further

**Comment by smuu** [comment]
The problem:
When calling `ExecuteCommand` in `PreparingState,` this command will be added to the `Dockerfile.` This `Dockerfile` is built when calling `Commit.`
As the command is not executed when calling the function, we cannot return anything to the caller. This might add confusion, as the caller expects the command's output.

**Comment by smuu** [comment]
One possible solution could be that when calling `ExecuteCommand` in `PreparingState`, we build the container, execute the command and then return the output.

**Comment by smuu** [comment]
cc @tty47 @mojtaba-esk

**Comment by mojtaba-esk** [comment]
> One possible solution could be that when calling `ExecuteCommand` in `PreparingState`, we build the container, execute the command and then return the output.

We could do that if there is a usecase for it. Or we could brake the function into two functions that one execute command on a running instance and one adds it to the instance and run it with delay when the instance starts. I think we already have the second one.
