### ISSUE TITLE
While running all the tests, they try to use a terminating namespace

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/knuu#370]
We are facing issues while running all the tests, the behavior is, that once the test is done, it removes the ns, but while running all the tests, they try to use the same (or at least that's what it looks like)

the error:
```
is forbidden: unable to create new content in namespace 20240523-155033-041 because it is being terminated
```

example:
https://github.com/celestiaorg/knuu/actions/runs/9211071205/job/25339558084#step:5:189

**Comment by mojtaba-esk** [comment]
I think I found the guilty code:

https://github.com/celestiaorg/knuu/blob/main/e2e/basic/build_from_git_test.go#L23-L25

It will be fixed when we merge [the knuu pkg refactor PR ](https://github.com/celestiaorg/knuu/pull/356) and use a fresh knuu object in this test.
