### ISSUE TITLE
On new major release, rename function to be more clear

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#38]
Do not work on this, only a new major release is planned

**Comment by smuu** [comment]
@smuu will go through the functions and create a proposal

**Comment by smuu** [comment]
Current list with all functions, the parameters, and the return type.

| Function Name                          | Parameters                                                                                     | Return                         |
|----------------------------------------|-----------------------------------------------------------------------------------------------|-------------------------------|
| AddCapabilities                        | capabilities []string                                                                         | error                         |
| AddCapability                          | capability string                                                                             | error                         |
| AddFile                                | src string, dest string, chown string                                                         | error                         |
| AddFileBytes                           | bytes []byte, dest string, chown string                                                       | error                         |
| AddFolder                              | src string, dest string, chown string                                                         | error                         |
| AddHost                                | ctx context.Context, port int                                                                 | host string, err error        |
| AddHostWithReadyCheck                  | ctx context.Context, port int, checkFunc func(host string) (bool, error)                      | host string, err error        |
| AddPolicyRule                          | rule rbacv1.PolicyRule                                                                        | error                         |
| AddPortTCP                             | port int                                                                                      | error                         |
| AddPortUDP                             | port int                                                                                      | error                         |
| AddSidecar                             | sidecar *Instance                                                                             | error                         |
| AddVolume                              | path string, size resource.Quantity                                                           | error                         |
| AddVolumeWithOwner                     | path string, size resource.Quantity, owner int64                                              | error                         |
| Clone                                  |                                                                                               | *Instance, error              |
| CloneWithName                          | name string                                                                                   | *Instance, error              |
| Commit                                 |                                                                                               | error                         |
| CreateCustomResource                   | ctx context.Context, gvr *schema.GroupVersionResource, ...                                    | error                         |
| CustomResourceDefinitionExists         | ctx context.Context, gvr *schema.GroupVersionResource                                         | bool, error                   |
| Destroy                                | ctx context.Context                                                                           | error                         |
| DisableBitTwister                      |                                                                                               | error                         |
| DisableNetwork                         | ctx context.Context                                                                           | error                         |
| EnableBitTwister                       |                                                                                               | error                         |
| EnableNetwork                          | ctx context.Context                                                                           | error                         |
| EnableTsharkCollector                  | conf TsharkCollectorConfig                                                                    | error                         |
| ExecuteCommand                         | ctx context.Context, command ...string                                                        | string, error                 |
| GetFileBytes                           | ctx context.Context, file string                                                              | []byte, error                 |
| GetIP                                  | ctx context.Context                                                                           | string, error                 |
| IsInState                              | states ...InstanceState                                                                       | bool                          |
| IsRunning                              | ctx context.Context                                                                           | bool, error                   |
| IsState                                | state InstanceState                                                                           | bool                          |
| K8sName                                |                                                                                               | string                        |
| Labels                                 |                                                                                               | map[string]string             |
| Name                                   |                                                                                               | string                        |
| NetworkIsDisabled                      | ctx context.Context                                                                           | bool, error                   |
| NewPool                                | amount int                                                                                    | *InstancePool, error          |
| PortForwardTCP                         | ctx context.Context, port int                                                                 | int, error                    |
| ReadFileFromRunningInstance            | ctx context.Context, filePath string                                                          | io.ReadCloser, error          |
| SetArgs                                | args ...string                                                                                | error                         |
| SetBandwidthLimit                      | limit int64                                                                                   | error                         |
| SetCPU                                 | request resource.Quantity                                                                     | error                         |
| SetCommand                             | command ...string                                                                             | error                         |
| SetEnvironmentVariable                 | key, value string                                                                             | error                         |
| SetGitRepo                             | ctx context.Context, gitContext builder.GitContext                                            | error                         |
| SetImage                               | ctx context.Context, image string                                                             | error                         |
| SetImageInstant                        | ctx context.Context, image string                                                             | error                         |
| SetInstanceType                        | instanceType InstanceType                                                                     |                               |
| SetJaegerEndpoint                      | grpcPort, thriftCompactPort, thriftHttpPort int                                               | error                         |
| SetJaegerExporter                      | endpoint string                                                                               | error                         |
| SetLatencyAndJitter                    | latency, jitter int64                                                                         | error                         |
| SetLivenessProbe                       | livenessProbe *v1.Probe                                                                       | error                         |
| SetMemory                              | request, limit resource.Quantity                                                              | error                         |
| SetOtelCollectorVersion                | version string                                                                                | error                         |
| SetOtelEndpoint                        | port int                                                                                      | error                         |
| SetOtlpExporter                        | endpoint, username, password string                                                           | error                         |
| SetPacketLoss                          | packetLoss int32                                                                              | error                         |
| SetPrivileged                          | privileged bool                                                                               | error                         |
| SetPrometheusEndpoint                  | port int, jobName, scapeInterval string                                                       | error                         |
| SetPrometheusExporter                  | endpoint string                                                                               | error                         |
| SetPrometheusRemoteWriteExporter       | endpoint string                                                                               | error                         |
| SetReadinessProbe                      | readinessProbe *v1.Probe                                                                      | error                         |
| SetStartupProbe                        | startupProbe *v1.Probe                                                                        | error                         |
| SetState                               | state InstanceState                                                                           |                               |
| SetUser                                | user string                                                                                   | error                         |
| Start                                  | ctx context.Context                                                                           | error                         |
| StartAsync                             | ctx context.Context                                                                           | error                         |
| StartWithCallback                      | ctx context.Context, callback func()                                                          | error                         |
| Stop                                   | ctx context.Context                                                                           | error                         |
| TsharkCollectorEnabled                 |                                                                                               | bool                          |
| WaitInstanceIsRunning                  | ctx context.Context                                                                           | error                         |
| WaitInstanceIsStopped                  | ctx context.Context                                                                           | error                         |

**Comment by smuu** [comment]
My proposal to rename functions:

EnableBitTwister -> EnableNetworkShaping
DisableBitTwister -> DisableNetworkShaping
K8sName -> UniqueName
NetworkIsDisabled -> IsNetworkDisabled
SetBandwidthLimit -> SetBandwidth
SetCommand -> SetStartCommand

Happy to discuss these @mojtaba-esk @tty47

**Comment by mojtaba-esk** [comment]
Good job. thanks for preparing that list, it helps to have a better look at them.

**Comment by smuu** [comment]
AddCapabilities -> AddKubernetesCapabilities
AddCapability -> AddKubernetesCapability

**Comment by mojtaba-esk** [comment]
Let's work on this once [the sidecar PR](https://github.com/celestiaorg/knuu/pull/443) is merged so we know what functions left to be renamed.

**Comment by mojtaba-esk** [comment]
PR #533  by default does some renaming as it groups different functions, let's have a look at the new structure (grouping) that is proposed by that PR and then see which one left to be renamed.
Also many of the functions listed above are moved to their own sidecar package so there might be none or just a few of them left to be renamed.
