### ISSUE TITLE
[Feature] Error codes should be constants

### ISSUE THREAD

**Issue by MSevey** [celestiaorg/knuu#398]
Knuu has very detailed errors with specific error codes. 

However these error codes are only defined in the errors themselves. This means that in order to use these error codes, you would need to string match which is error prone. 

Instead, the error codes themselves should be exported constants so that they can be explicitly matched.

**Comment by mojtaba-esk** [comment]
instead we can make the user's life easier by adding an `Is` function so users do not have to cast errors and compare codes themselves.
