### ISSUE TITLE
[Feature] Improved Errors Type

### ISSUE THREAD

**Issue by MSevey** [celestiaorg/knuu#400]
Right now the way these errors are being defined and used is quite error prone, specifically as it relates to how we are using the message and params. If a developer doesn't correctly match the number of formatting directives in the message, it will panic when `Error` is called. 

We can do better :-) 

First, we should have a `New` method as that is much safer than manually defining the structs. 

Second we should make the params more dynamic. 

## New Method

The new method should be something like this.

```go
// We should also add some type safety here
type Code string

func New(code Code, msg string) (Error, error) {
	e := Error{Code: code, Message: msg}

       
	err = e.validate()
        if err != nil {
               return nil, err
        }
	return e, nil
}

func (e *Error) validate() error {
        defer func() {
            if r := recover(); r != nil {
                return fmt.Errorf("invalid Error: %v",r)
            }
        }()
        _ = e.Error()
        return nil
}
```

## Dynamic Params

Instead of relying on a fixed formatted method, we could allow for dynamic params by expecting a key value pair. 

```go
func (e *Error) WithParams(params ...interface{}) {
	if len(params)%2 != 0 {
                // Using panic for simplicity of example, but this is a discussion point as to how to handle the error
		panic("Error: Odd number of parameters, expected key-value pairs")
	}
        e.Params = append(e.Params, params...)
        return e
}

func (e *Error) Error() string {
	msg := e.Message
	for i := 0; i < len(e.Params); i += 2 {
		key := params[i]
		value := params[i+1]
		msg = fmt.Sprintf("%s; %v: %v",msg, key, value)
	}
	if e.Err != nil {
		return fmt.Sprintf("%s; error: %v", msg, e.Err)
	}
	return msg
}
```

**Comment by mojtaba-esk** [comment]
Saw your comment about creating an issue a bit late, I have applied those on the original PR.

**Comment by MSevey** [comment]
> Saw your comment about creating an issue a bit late, I have applied those on the original PR.

Thanks for adding the New method, that is a good start. 
I think there are still other parts of this issue that we should discuss. 
Lower priority though.

**Comment by smuu** [comment]
done
