### ISSUE TITLE
if the testscope is empty, the SanitizeName will panic, but the expected behaviour is to fill it with the default scope.

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#485]
if the testscope is empty, the SanitizeName will panic, but the expected behaviour is to fill it with the default scope.

_Originally posted by @mojtaba-esk in https://github.com/celestiaorg/knuu/pull/465#discussion_r1661170389_

**Comment by mojtaba-esk** [comment]
This is fixed

**Comment by smuu** [comment]
It might be an issue again. It needs to be checked.
