### ISSUE TITLE
Consider grouping of instance functions.

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#519]
Groups to introduce: `networkShaping` and `observability`

To call functions of such a group, the dev would call: `instance.<groupName>.<functionName>`

This could improve the understanding of the usage of different functions.

networkShaping
- EnableBitTwister/EnableNetworkShaping
- DisableBitTwister/DisableNetworkShaping
- SetLatencyAndJitter
- SetPacketLoss
- SetBandwidthLimit

observability:
- SetJaegerEndpoint
- SetJaegerExporter
- SetOtelCollectorVersion
- SetOtelEndpoint
- SetOtlpExporter
- SetPrometheusEndpoint
- SetPrometheusExporter
- SetPrometheusRemoteWriteExporter

Please let me know what you think @mojtaba-esk and @tty47

**Comment by mojtaba-esk** [comment]
This makes sense, however those two that are listed as examples, i.e. networkShaping & Observeability are extracted in [this PR](https://github.com/celestiaorg/knuu/pull/443) to sidecars hens makes it tidy and concise.
But I do agree with grouping other functions that are not extracted to other packages yet.

**Comment by smuu** [comment]
> This makes sense, however those two that are listed as examples, i.e. networkShaping & Observeability are extracted in [this PR](https://github.com/celestiaorg/knuu/pull/443) to sidecars hens makes it tidy and concise. But I do agree with grouping other functions that are not extracted to other packages yet.

You are right 👍 

What other functions would you group?

**Comment by mojtaba-esk** [comment]
Let's start to work on this once [the sidecar PR](https://github.com/celestiaorg/knuu/pull/443) is merged so we know what functions left to be renamed.

**Comment by mojtaba-esk** [comment]
cc: @tty47
