### ISSUE TITLE
feat: `CloneWithSuffix` does not check for Instance state

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#531]
`Clone` checks for state Instance is in but `CloneWithSuffix` does not.

https://github.com/celestiaorg/knuu/blob/f21844326cbab7ac02332612a2aafddadd9ea0dd/pkg/instance/instance.go#L1074

https://github.com/celestiaorg/knuu/blob/f21844326cbab7ac02332612a2aafddadd9ea0dd/pkg/instance/helper.go#L375

**Comment by mojtaba-esk** [comment]
This might be fixed by #530

**Comment by mojtaba-esk** [comment]
> I think this is already done in the PR merged, right?

Thanks for pointing it out. I am merging #570 as it has two approvals. So then we cal close it
