### ISSUE TITLE
Instance should be able to stop and restart

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/knuu#55]
I want to simulate a network with rotating outages. For this, I will need nodes to go down and then bring them back.

**Comment by jrmanes** [comment]
hey @cmwaters 😄 

maybe for this use case, the Robusta environment is better, there, you can remove nodes and Kubernetes will bring them back again automatically, not sure if we can simulate this with knuu

cheers!

**Comment by cmwaters** [comment]
I think what I might try is just deleting the pod, waiting a while and deploying it again

**Comment by jrmanes** [comment]
yap! I think this might work, let me know if you need any support from our side

**Comment by smuu** [comment]
It should be quite easy to add something like `Stop()` which keeps the data and when you call `Start()` again it's get started again with the same data. (This requires to use `AddVolume()` to specify which data you want to keep.) Will dig into this the next days.

**Comment by cmwaters** [comment]
How do I add a volume? 

Would be great for me at least if I could build the file directory for a node and just attach it rather than adding all the files separately

**Comment by smuu** [comment]
> Is it possible to have a shared volume?
> 
> Would be great for me at least if I could build the file directory for a node and just attach it rather than adding all the files separately

Do you mean running multiple instances with the same volume or creating a volume and cloning and reusing it for multiple instances?

**Comment by cmwaters** [comment]
Actually I was referring to how Tendermint does it where you make the directory and then link it as the volume in the dockerfile but this probably doesn't work remotely so I take that back. Perhaps what would be nice is if instead of copying all the individual files across, I can copy the entire directory. If you look at the PR on [app](https://github.com/celestiaorg/celestia-app/pull/1914) I have to make the directories and copy all the individual files across

**Comment by smuu** [comment]
I just checked `AddFile()` again, and it seems that you could add a full directory with it as well. The name does not indicate that, so thinking about renaming it or adding an additional function.

**Comment by smuu** [comment]
> I want to simulate a network with rotating outages. For this, I will need nodes to go down and then bring them back.

Do you want to simulate a network outage or node outage? For network outages, I could add a function that disables/enables all communication from and to that Instance without stopping it. I nevertheless add the `Stop()` functionality as it makes sense to have it.

**Comment by smuu** [comment]
> Actually I was referring to how Tendermint does it where you make the directory and then link it as the volume in the dockerfile but this probably doesn't work remotely so I take that back. Perhaps what would be nice is if instead of copying all the individual files across, I can copy the entire directory. If you look at the PR on [app](https://github.com/celestiaorg/celestia-app/pull/1914) I have to make the directories and copy all the individual files across

I tested it and with `AddFile()` you can also add Folders. See here: https://github.com/celestiaorg/knuu-example/blob/feature/file-folder-testing/basic/folder_test.go#L32

**Comment by smuu** [comment]
> > Actually I was referring to how Tendermint does it where you make the directory and then link it as the volume in the dockerfile but this probably doesn't work remotely so I take that back. Perhaps what would be nice is if instead of copying all the individual files across, I can copy the entire directory. If you look at the PR on [app](https://github.com/celestiaorg/celestia-app/pull/1914) I have to make the directories and copy all the individual files across
> 
> I tested it, and with `AddFile()`, you can also add directories. See here: https://github.com/celestiaorg/knuu-example/blob/feature/file-folder-testing/basic/folder_test.go#L32

The next release will have an `AddFolder()` function that is an synonym for `AddFile()`: https://github.com/celestiaorg/knuu/pull/77
